### ISSUE TITLE
add_value_labels replaces the list of value labels instead of updating it when called inside another function

### ISSUE THREAD

**Issue by jdjohn215** [larmarange/labelled#103]
When reconciling survey waves, I sometimes I need to recode a lot of values and their corresponding labels. Here's an example.

```
# some test data
df <- tibble(s1 = c("M", "M", "F","F"), s2 = c(1, 1, 2, 9)) %>%
  set_value_labels(s1 = c(Male = "M", Female = "F"), s2 = c(Yes = 1, No = 2, Unknown = 9))
```

Let's say I want to recode `s2 = 9` to `s2 = 99`. I also want to move the value label. Because I'm doing this exact same recode for lots of variables, I wrote a function to do both steps.

```
recode_val_label <- function(data, varname){
  data %>%
    mutate({{varname}} := ifelse({{varname}} == 9, 99, {{varname}})) %>%
    add_value_labels({{varname}} := c(
      "Unknown" = 99
    ))
}
```

But this function behaves like `set_value_labels`. It removes all the other labels besides 99.

`df %>% recode_val_label(s2)`
```
# A tibble: 4 × 2
  s1                   s2
  <chr+lbl>     <dbl+lbl>
1 M [Male]    1          
2 M [Male]    1          
3 F [Female]  2          
4 F [Female] 99 [Unknown]
```

I apologize if I'm missing something obvious here.

**Comment by jdjohn215** [comment]
Woops, I apologize. I realize now the problem is that using `ifelse` on a labelled variable turns it into a numeric variable.

**Comment by larmarange** [comment]
You could have a look to
https://larmarange.github.io/labelled/reference/recode_if.html

This function should not convert the variable

Joseph Larmarange

Le lun. 26 juil. 2021 à 03:50, John D. Johnson ***@***.***> a
écrit :
