### ISSUE TITLE
Labelled Cheatsheet Typo - to_factor(x)

### ISSUE THREAD

**Issue by AbhinavSKrishnan** [larmarange/labelled#112]
On page 2 of the Labelled cheatsheet, the description for to_factor(x) reads "convert into a character vector" instead of "convert into a factor vector" (see below).

<img width="467" alt="Screen Shot 2021-12-02 at 10 47 27" src="https://user-images.githubusercontent.com/72804566/144466081-d0185aff-5395-4cf0-bf38-662f1757f15d.png">

**Comment by larmarange** [comment]
Thanks for the report. It has been fixed.

cf. https://github.com/larmarange/labelled/raw/main/cheatsheet/labelled_cheatsheet.pdf
