### ISSUE TITLE
add var_description() function

### ISSUE THREAD

**Issue by vorpalvorpal** [larmarange/labelled#113]
The dataMaid (and possibly other?) packages uses a "shortDescription" attribute for providing a bit more detail about a variable that what is included in a label. For example, for the `iris` dataset, the variable Species might have a label of "Species of the genus Iris" and a description of "Species names from the time that the dataset was originally recorded. Note that *Iris versicolor f. virginica (L.) Voss* is a synonym of *I. virginica*."

It would be nice if the` var_label` and `set_variable_label` functions provided by labelled were replicated as `var_description` and `set_variable_description` to set the "shortDescription" attribute.

**Comment by larmarange** [comment]
Thank you for your proposal.

`labelled` is focused on `haven_labelled` and `haven_labelled_spss` class introduced by `haven`. Therefore, the philosophy is to consider **only** attributes managed by `haven`, as well as variable labels also managed by `haven` and taken into account in the **RStudio** ecosystem.

If I understand the need for a descriptive field, I would say that this is not (currently) in the scope of `labelled`. It is not just the development of `var_description()` and `set_variable_description()` (easy to implement, and you can copy the current code available in `labelled`), but it raises several question:

- what should be the name of the attribute? `description`? `shortDescription`? There is no specific consensus about the way to manage metadata in R and we can already see several packages following several conventions. If such attributes emerge in **RStudio** or **tidyverse** ecosystems, then `labelled` could consider it.
- printing methods and visualisation tools should be developed as well. Right now, `labelled` do not manage the printing of variable and value labels as it is already covered by the **tidyverse**.

Another package proposing a way to include metadata is `memisc`: <http://www.elff.eu/software/memisc/items/>  It does propose a way to add a description to an item. Please note however that `memisc` is using another way of storing metatadata than `labelled`. Therefore, both packages are not compatible.
