### ISSUE TITLE
Variable label disappears only following certain changes to variable

### ISSUE THREAD

**Issue by jcutlerbiostats** [larmarange/labelled#122]
I was wondering if there was something I could do to preserve variable labels no matter what changes I make to the variable. I don't understand why variable labels are preserved through some changes and not others. For example:

library(tidyverse)
library(labelled)

mtcars <- mtcars %>% 
  as_tibble() %>% 
  set_variable_labels(
    qsec = "Q Sec Label"
  )

mtcars %>% var_label()

mtcars %>% 
  mutate(qsec = log(qsec)) %>% 
  var_label()

mtcars %>% 
  mutate(qsec = cumsum(qsec)) %>% 
  var_label()

The variable labels are lost after a cumsum() change but not after a log() change. Is there a way to make it not drop the variable label?

**Comment by larmarange** [comment]
`cumsum()` and all cumulative functions do not preserve attributes attached to a vector.
They take a vector and generate a completely new vector. Therefore, variable labels are not preserved.

However, this behaviour is not unexpected, as `cumsum(x)` is not the same as `x` and there is no reason to preserve a variable label that should be updated anyway.

So far, if you want to preserve that specific label, you have to store it and to resave it.

Regards

**Comment by larmarange** [comment]
You may be interested by `copy_labels_from()`:

``` r
library(tidyverse)
library(labelled)

mtcars <- mtcars %>%
  as_tibble() %>%
  set_variable_labels(
    qsec = "Q Sec Label"
  )

mtcars %>%
  mutate(qsec = cumsum(qsec)) %>%
  copy_labels_from(mtcars) %>%
  var_label()
#> $mpg
#> NULL
#> 
#> $cyl
#> NULL
#> 
#> $disp
#> NULL
#> 
#> $hp
#> NULL
#> 
#> $drat
#> NULL
#> 
#> $wt
#> NULL
#> 
#> $qsec
#> [1] "Q Sec Label"
#> 
#> $vs
#> NULL
#> 
#> $am
#> NULL
#> 
#> $gear
#> NULL
#> 
#> $carb
#> NULL
```

<sup>Created on 2022-06-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by larmarange** [comment]
Alternatively

``` r
library(tidyverse)
library(labelled)

mtcars <- mtcars %>%
  as_tibble() %>%
  set_variable_labels(
    qsec = "Q Sec Label"
  )

l <- var_label(mtcars)

mtcars %>%
  mutate(qsec = cumsum(qsec)) %>%
  set_variable_labels(.labels = l, .strict = FALSE) %>%
  var_label()
#> $mpg
#> NULL
#> 
#> $cyl
#> NULL
#> 
#> $disp
#> NULL
#> 
#> $hp
#> NULL
#> 
#> $drat
#> NULL
#> 
#> $wt
#> NULL
#> 
#> $qsec
#> [1] "Q Sec Label"
#> 
#> $vs
#> NULL
#> 
#> $am
#> NULL
#> 
#> $gear
#> NULL
#> 
#> $carb
#> NULL
```

<sup>Created on 2022-06-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
