### ISSUE TITLE
Request Feature - Fill data frame column labels

### ISSUE THREAD

**Issue by dereksonderegger** [larmarange/labelled#131]
It is not uncommon to import a data frame with some columns containing label information and but others to be missing that information. To facilitate downstream actions (e.g. using the gt package that still doesn't handle attribute column labels gracefully), it would be useful to be able to copy the column names to the column labels for columns that are missing the label.

I was looking around both the labelled and sjlabelled packages to find this functionality and didn't see anything. My initial stab at the function is below. Feel free to ignore, modify, or integrate this request as you like. If you'd prefer this as a pull request, I could do that, too. 

    #' Fill data frame missing column label attributes with column name
    #' 
    #' Many SAS and SPSS data sets come with the label attribute 
    #' set for the columns, however some columns might lack those
    #' labels. For those columns, this function fills in the label
    #' with the column name.
    #' 
    #' @param df A data frame
    #' @examples
    #' iris |>
    #'   labelled::set_variable_labels( 
    #'     Sepal.Length = "Sepal Length",
    #'     Species = "Iris Species") |>
    #'   fill_variable_labels() |>
    #'   labelled::var_label()
    #' @export
    fill_variable_labels <- function(df){  
      col_names  <- df |> colnames() 
      col_labels <- df |> 
        labelled::var_label() |> 
        purrr::map( ~ ifelse(is.null(.), '..WAS_NULL..', .) ) |> 
        purrr::as_vector()
      
      out_labels <- ifelse( col_labels == '..WAS_NULL..', col_names, col_labels)
      
      out <- df |>
        labelled::set_variable_labels( .labels = map(out_labels, ~.) )
      return(out)
    }

**Comment by larmarange** [comment]
Hi. Thank you for your comment.

Would you have some concrete examples when you would need such feature?

Regarding what you said about `gt`, I could understand the need of a function renaming columns by their variable label (when it exists), but I do not see the point of populating variable labels when it is missing. But I may miss something.

Maybe, as a first step, it could be possible to add an option `fill_null` to `var_label()`, only when applied on a data.frame, to return the column name instead of NULL when where is no variable label.

**Comment by dereksonderegger** [comment]
Hi.  I'm in a situation where I import SAS datasets and some of the columns have labels and some of them don't. We should use those labels whenever possible for consistency in our reporting. However, the gt package doesn't check for labels and instead you need to do something with gt::cols_label(). 

    df %>%
    gt::cols_label( .list = labelled::var_label(x=.$`_data`)

But this solution requires that *all* the columns have labels or to remove any NULL values in the output of `var_label()`. The removal of the NULL values isn't too bad using `|> purrr:discard(is.null)` but it feels like there could be other situations where the software requires setting all of the labels.

Thinking about your `var_label()` solution, I really like having the option of a) filling the null values with the variable name, or b) not including the null values.  So something like `null_action = c('keep', 'fill', 'skip')`  where the default 'keep' option does exactly what it does now, `fill` fills in the column name, and `skip` removes the element with missing label.

This fits with the idea that labels, if they exist, should always be informative and not created arbitrarily, but also allows for the flexibility to handle columns gracefully when the labels don't exist.

**Comment by larmarange** [comment]
Could you have a look at #132 ?
Would it fix your issue?

**Comment by dereksonderegger** [comment]
This proposed solution in #132 is by far the most elegant solution and will help others in the future and will make `labelled` easier to use in conjunction with other packages.

For my particular issues, I can make it work either using my hacked together solution or adding a purrr::discard() step afterwards so I'm not stuck.
 
Thank you so much for the package and for your elegant solution.

**Comment by larmarange** [comment]
With this change, it is easy to create a `fill_variable_labels()` function for your specific need:

``` r
library(labelled)

fill_variable_labels <- function(x) {
  x %>%
    set_variable_labels(
      .labels = var_label(x, null_action = "fill")
    )
}

df <- datasets::iris %>%
  set_variable_labels(
    Petal.Length = "length of petal",
    Petal.Width = "width of petal"
  )

df %>%
  look_for()
#>  pos variable     label           col_type values    
#>  1   Sepal.Length —               dbl                
#>  2   Sepal.Width  —               dbl                
#>  3   Petal.Length length of petal dbl                
#>  4   Petal.Width  width of petal  dbl                
#>  5   Species      —               fct      setosa    
#>                                            versicolor
#>                                            virginica

df %>%
  fill_variable_labels() %>%
  look_for()
#>  pos variable     label           col_type values    
#>  1   Sepal.Length Sepal.Length    dbl                
#>  2   Sepal.Width  Sepal.Width     dbl                
#>  3   Petal.Length length of petal dbl                
#>  4   Petal.Width  width of petal  dbl                
#>  5   Species      Species         fct      setosa    
#>                                            versicolor
#>                                            virginica
```

<sup>Created on 2022-12-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dereksonderegger** [comment]
This works beautifully and I've incorporated it into a workflow and added it to my company's suggested solutions documentation. I'm surprised you were able to address and push this so quickly!
