### ISSUE TITLE
functions compatible with %>%

### ISSUE THREAD

**Issue by larmarange** [larmarange/labelled#14]
Following https://github.com/hadley/haven/issues/185, some functions for variable and value labels that could be used with `%>%` operator.

**Comment by jjchern** [comment]
Again, thank you for working on this function. Do you think the same logic can be applied to adding variable label? `add_var_label`?

**Comment by larmarange** [comment]
It is possible to write a function with the same logic than `var_label`, i.e. who update value labels, rather than replace them. However, I'm not sure in terms of names, as `add_var_labels` and `add_var_label` will probably be confusing.

Would it be better to use instead `replace_val_labels` and `update_val_labels` ?

**Comment by larmarange** [comment]
or `add_val_labels` for updating the labels and `set_val_labels` to replace them?

**Comment by larmarange** [comment]
I have finally implemented the three new functions `set_variable_labels()`, `set_value_labels()` and `add_value_labels()` .
