### ISSUE TITLE
Unclassing should not occur on val_labels(x) <- NULL (or when setting to empty vector)

### ISSUE THREAD

**Issue by torfason** [larmarange/labelled#145]
Setting `val_labels(x) <- NULL` triggers an unclassing of a `haven_labelled` variable. I would argue that this is not in line with the (admittedly very limited) specification of `haven_labelled` that is presented in https://haven.tidyverse.org/reference/labelled.html . Specifically: "labels: A named vector or NULL. The vector should be the same type as x. Unlike factors, labels don't need to be exhaustive: only a fraction of the values might be labelled."

In other words, either `NULL` or a zero-length vector are acceptable as value labels, and in fact, both can be set using the `haven::labelled()` constructor.

I would prefer to use the `val_labels()` / `var_label()`  as getters and setters for `haven_labelled` labels in derived code, but the practical implication of the above is that with this current implementation, it is not possible to rely on `val_labels()<-` for setting labels that are programmatically generated and can end up being empty. 

More details in the form of a reprex below:

``` r
# I would argue that setting val_labels(x) to NULL or empty vector
# are both perfectly valid and should not trigger the stripping
# of the class attribute.
labelled:::`val_labels<-.haven_labelled`
#> function (x, value) 
#> {
#>     if (length(value) == 0) 
#>         value <- NULL
#>     if (is.null(value)) {
#>         x <- unclass(x)
#>         attr(x, "labels") <- NULL
#>     }
#>     else {
#>         x <- labelled(x, value, label = var_label(x))
#>     }
#>     x
#> }
#> <bytecode: 0x7f7a95df2710>
#> <environment: namespace:labelled>

library(labelled)

# Usually constructor and val_labels()<- are equivalent

X <- labelled(letters, c(a = "The letter a"))
str(X)
#>  chr+lbl [1:26] a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t,...
#>  @ labels: Named chr "The letter a"
#>   ..- attr(*, "names")= chr "a"

Y <- labelled(letters)
val_labels(Y) <- c(a = "The letter a")
str(Y)
#>  chr+lbl [1:26] a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t,...
#>  @ labels: Named chr "The letter a"
#>   ..- attr(*, "names")= chr "a"

waldo::compare(X, Y)
#> ✔ No differences

# With empty labels vectors,
# the constructor works but val_labels()<- does not,
# and neither does set_value_labels()

empty_named <- character() |> setNames(character())

x <- labelled(letters, labels=empty_named)
str(x)
#>  chr+lbl [1:26] a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t,...
#>  @ labels: Named chr(0) 
#>   ..- attr(*, "names")= chr(0)

y <- labelled(letters)
val_labels(y) <- empty_named
str(y)
#>  chr [1:26] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" ...

z <- labelled(letters)
z <- set_value_labels(z, empty_named)
str(z)
#>  chr [1:26] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" ...

waldo::compare(x, y)
#> `old` is an S3 object of class <haven_labelled/vctrs_vctr/character>, a character vector
#> `new` is a character vector ('a', 'b', 'c', 'd', 'e', ...)
waldo::compare(x, z)
#> `old` is an S3 object of class <haven_labelled/vctrs_vctr/character>, a character vector
#> `new` is a character vector ('a', 'b', 'c', 'd', 'e', ...)
```

<sup>Created on 2023-07-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
Dear @torfason 

somehow, it would be a major change. Do you have any example where you would need an haven_labelled vector with no value labels?

As a reminder, the haven_labelled class has been introduced by haven when importing data from SAS, SPSS and Stata. The `labelled()` constructor is used by **haven** ONLY when a variable has a value label attached to it. If there are no value labels, the variable is imported as a character or as a numeric vector. For **haven** package, the `haven_labelled` class was intended only as a temporary class when importing data.

When designing the **labelled** package, the purpose was to provide functions to manipulate such vectors. If you attach value labels to a character or a numeric vector, such vector is transformed to an `haven_labelled` vector, i.e. a vector with value labels. And similarly, if you remove value labels, then the vector is transformed back to a simple character or numeric vector, i.e. a vector with no value labels.

I admit that `haven::labelled()` allows to construct an `haven_labelled` vector with no value labels attached. But, in practice, it is never used by **haven**.

Do you have any user case when `haven_labelled` vectors with no value label would be useful?

**Comment by torfason** [comment]
Thanks for a quick response.

My use case is that I am drafting [`forlabs`](https://torfason.github.io/forlabs/), a small package with functions for labelled variables that are analogous to those in the forcats package (for factors). It's not that I am specifically aiming to create labelled variables with a NULL value labels, but that functions, such as lbl_drop() might end up removing the last tagged level. Or a function might be called with a variable that was constructed using labelled() with only a variable label and no value label. For example, someone might create a variable manually for manipulation and export to SPSS or other formats. And then the result of a function would also have a NULL variable label, but then when the function sets the label again, the class gets zapped. I got bitten by this in a test and was pretty surprised.

I can work around this by setting the labels manually using attr(), or by just always recreating the result with a new set of labels, it was more that it would have been nice to use the convenient setter functions.

And that I felt was the most logical functionality. However, I agree that it is a non-backwards-compatible change, and if people have been using this approach to zap the class then they would be bitten by it.

So I do understand if backwards compatibility considerations prevent changing this :-)

**Comment by larmarange** [comment]
If you have a use for it, it is possible to add a parameter named preserve to var_labels(). FALSE by default. If TRUE, haven_labelled would be preserved.

**Comment by larmarange** [comment]
Dear @torfason 

could you have a look at #146 and the new `null_action` argument? Would it solve your issue?

**Comment by larmarange** [comment]
As it is now implemented, it is easy to integrate
