### ISSUE TITLE
set_variable_labels list problem

### ISSUE THREAD

**Issue by ipuzek** [larmarange/labelled#15]
Hi!

If i provide a named list of values to set_variable_labels(), it does not work because it converts the list into a list. This makes it impossible to follow the efficient workflow of...

1) get variable labels via var_label(data)
2) manipulate data, lose the variable labels in the process
3) reapply variable names via set_variable_labels

The problem is the first line in set_variable_labels: `values <- list(...)`

**Comment by larmarange** [comment]
Could you please provide a concrete example of usage?

`set_variable_labels` should be used only with the pipe `%>%`.

If you want to copy labels from `df1` to `df2` (because you lost labels at some point):

```r
df2 <- copy_labels(df1, df2)
```

**Comment by ipuzek** [comment]
OK, I was not aware of copy_labels(). It would probably be a good solution for my case (which I do not have ready at the moment). Thanks!
