### ISSUE TITLE
Idea: implement `set_var_labels_with`

### ISSUE THREAD

**Issue by ABohynDOE** [larmarange/labelled#163]
Firstly, I really enjoy this package ! I mainly use the `set_var_labels()` function to define variable labels to obtain nice summary tables with `gtsummary`.

However, I often think that it would be useful to have a function that sets variable labels based on the column names and that can be applied in the same way as `rename_with()`  works. 

For example, if I have a data frame with columns `quest_1` to `quest_10`, and `location_A` to `location_Z`, I wish there was a function I could use to do:

```{r}
labelled_df <- df %>%
  set_var_labels_with(
    .fn = ~paste0("Question ", str_extract(.x, "\\d+$")),
    .cols = starts_with("quest_")
  ) %>% 
  set_var_labels_with(
    .fn = ~paste0("Location ", str_extract(.x, ".$")),
    .cols = starts_with("location_")
  )
```

Of course this is maybe a silly example, but I think that it could allow labelling variables within a pipe workflow, without having to manually generate labels when there are many columns.

**Comment by larmarange** [comment]
There is already an `update_variable_labels_with()` function provided by `labelled`. With #164, variable names are now accessible using `names()`.

``` r
library(labelled)

iris |> 
  update_variable_labels_with(~ toupper(names(.x))) |> 
  look_for()
#>  pos variable     label col_type missing values    
#>  1   Sepal.Length —     dbl      0                 
#>  2   Sepal.Width  —     dbl      0                 
#>  3   Petal.Length —     dbl      0                 
#>  4   Petal.Width  —     dbl      0                 
#>  5   Species      —     fct      0       setosa    
#>                                          versicolor
#>                                          virginica
```

<sup>Created on 2024-10-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by ABohynDOE** [comment]
OK thanks a lot, I didn't find this function earlier !
