### ISSUE TITLE
plans for extending support of formats

### ISSUE THREAD

**Issue by kkmann** [larmarange/labelled#18]
Hi,

I recently started to use `labelled` more frequently and find it a bit difficult to switch between representation as labelled vector and `factors`. Internally, many functions require `factors`, but factors are not as flexible as labelled vectors. So it would be nice to define a new `format` class for converting between the two. I.e., have something like 

    x <- labelled(c(1,2,2), labels = c(1 = "x", 2 = "y"))
    fmt <- format(x)
    x_fct <- as_factor(x)
    xx <- as_labelled(x_fct, fmt)

where  `xx == x` holds. This would allow keeping the data in as labelled vectors with values as specified in the database and switching back and forth between factors and labelled vectors as needed. Are there any plans in this direction or would you accept a pull request?

Best, 

Kevin

**Comment by larmarange** [comment]
Hi Kevin,

as you may have noticed, to avoid conflict with `haven`, the `labelled` package proposes two methods `to_factor` and `to_labelled`.  The `to_labelled` method could be applied to a factor. However, for now, there is no option to specify a specific coding.

We could propose an additional `labels` argument with the same format than the one used in `labelled` function (and same format than provided by `val_labels`) to specify how the levels of the factor should be encoded. 

A `format` class would not be necessary. Please note that `format` is already a specific base R class.

**Comment by larmarange** [comment]
See commit. Now you can do:

```r

> library(labelled)
> s1 <- labelled(c('M', 'M', 'F'), c(Male = 'M', Female = 'F'))
> labels <- val_labels(s1)
> f1 <- to_factor(s1)
> f1
[1] Male   Male   Female
Levels: Male Female
> 
> to_labelled(f1)
<Labelled double>
[1] 1 1 2

Labels:
 value  label
     1   Male
     2 Female
> identical(s1, to_labelled(f1))
[1] FALSE
> to_labelled(f1, labels)
<Labelled character>
[1] M M F

Labels:
 value  label
     M   Male
     F Female
> identical(s1, to_labelled(f1, labels))
[1] TRUE
```
