### ISSUE TITLE
bind_rows(), list columns and var_labels

### ISSUE THREAD

**Issue by mbojan** [larmarange/labelled#19]
I need to `bind_rows()` of two tibbles that contain labelled data and list columns. dplyr is dropping the labels with a warning about "Vectorizing labelled data". To circumvent this I am trying to extract the lists of variable labels and value labels and re-applying them to the binded tibble. This does not work for variable labels and list columns unfortunately (see the reprex below).

What do you think about:

1. `var_label()` actually does not need to check whether `x` is atomic, doesn't it? The test could be dropped IMHO.
2. a more general solution for binding rows of labelled data. The question is of course what if value labels for the same variables in both data frames are different. Perhaps it could be handled similarly to factor levels. This would be a dplyr issue anyway...

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(haven)
library(labelled)

d <- data_frame(
  x = labelled(1:5, c(a=1, b=5)),
  lc = as.list(1:5)
)
var_label(d$x) <- "This is x"

# Can't apply variable label to a list column
var_label(d$lc) <- "This is lc" # Why not actually?
#> Error: `x` should be atomic



# Extract value labels
vl <- val_labels(d)

# Bind rows and re-apply value labels
dd <- bind_rows(d, d, .id="copy") 
#> Warning in bind_rows_(x, .id): Vectorizing 'labelled' elements may not
#> preserve their attributes

#> Warning in bind_rows_(x, .id): Vectorizing 'labelled' elements may not
#> preserve their attributes
val_labels(dd) <- vl
dd$x # OK!
#> <Labelled integer>
#>  [1] 1 2 3 4 5 1 2 3 4 5
#> 
#> Labels:
#>  value label
#>      1     a
#>      5     b


# Can't extract variable labels
# because d$lc is not atomic
var_label(d)
#> Error: `x` should be atomic
# This can be done "manually" along the following lines
varlabs <- lapply(d, attr, "label")
var_label(dd) <- varlabs[1] # skip the list column
lapply(dd, attr, "label")
#> $copy
#> NULL
#> 
#> $x
#> [1] "This is x"
#> 
#> $lc
#> NULL
```

**Comment by larmarange** [comment]
Hello,

`var_label` has been updated to accommodate any type of object (cf. 
https://github.com/larmarange/labelled/commit/40fdfccb226285a8edc756e83f79b431baeac8b1)

Regarding your second comment, there is no unique solution. There are fundamental differences between factors and labelled vectors. For labelled vectors, the importance is the original value, labels are just additional meta data while for factors the data is stored in the levels, not the underlying codes. 

You can use `copy_labels` function to copy variable and value lables from one data.frame to another data.frame.

Regards

**Comment by mbojan** [comment]
Thanks!
