### ISSUE TITLE
How does `val_labels(v) <- value` work?

### ISSUE THREAD

**Issue by sjPlot** [larmarange/labelled#2]

**Comment by larmarange** [comment]
`val_labels(v) <- value` allows you to set all the value labels in one call.  `value` should be a named vector exactly like the `labels` argument of the `labelled` function. If required, the class of the vector will be changed to `labelled`, or removed if `value` is NULL.

All labels should be part of `values`, i.e. if a label is not present and was previously declared, it will be removed.

Concerning missing values, the situation depends of previously defined value labels:
- if the value labels was already defined, the corresponding status about missing values is preserved;
- if it's a new value label, it's not considered as a missing value;
- if a previously value label was defined and is not defined any more, that label is deleted (and the corresponding attached missing value status).

Is it clear enough?

**Comment by sjPlot** [comment]
Yes, got it. Thanks!
