### ISSUE TITLE
Check matching type

### ISSUE THREAD

**Issue by rubenarslan** [larmarange/labelled#28]
This is a little annoying, especially because most haven functions do not complain. Maybe you could check the type in `val_labels` and cast it correctly if possible or throw an error if not?

```r
x = 1L:5L
labelled::val_labels(x) <-  c("low" = 1)
haven::na_tag(x)
```

> Error: `x` must be a double vector

**Comment by larmarange** [comment]
Hi Ruben,

this issue seems not related to `labelled` but rather to `haven`.

``` 
haven::na_tag(1L:5L)
```

>Error: `x` must be a double vector
