### ISSUE TITLE
Add a set_variable_labels_all function to create labels from column names using a specified function 

### ISSUE THREAD

**Issue by karissawhiting** [larmarange/labelled#35]
It would be very useful to have a function that automatically sets all data.frame labels as transformed versions of the column names. Similar to the janitor package's `clean_names()` function that creates and sets snakecase column names, I would like to be able to set all column labels to a readable version of the column names from within a pipe. (Usually I am transforming from snakecase to title case and replacing "_" with  spaces). 

I could see two approaches to this:

1) The more straight forward but less flexible approach would be to allow the user a limited set of pre-defined transformation options (e.g. title case, all caps, replace "_" with " ").

2) Allow a user to use any function to transform. I'm not sure the best way to do this, but perhaps it could employ some of the tools underlying `rename_all()` in dplyr: (https://github.com/tidyverse/dplyr/blob/master/R/funs.R)

**Comment by larmarange** [comment]
Do you have a concrete example? Not sure to fully understand what you mean.

Regards

**Comment by karissawhiting** [comment]
```
library(tidyverse)

test_data <- tribble(
  ~age, ~gender, ~smoking_status,
  62,     "F",      "Smoker", 
  55,     "M",      "Non-Smoker", 
  40,     "F",      "Smoker"
)

make_label  <- function(x) {
  x %>%
    str_replace(., "_", " ") %>%
    toTitleCase() %>%
    return()
}

new_test_data <- test_data %>%
  select(gender, smoking_status) %>%
  set_variable_labels_all(funs(make_label)) 

var_label(new_test_data)
 ```

And the desired output would be:

```
$gender
[1] "Gender"

$smoking_status
[1] "Smoking Status"
```

Please let me know if you need more clarification, thanks!

**Comment by larmarange** [comment]
OK. I guess that your proposal is inspired by `dplyr::rename_all()`.

However, I'm not sure if this is the appropriate way to deal with it. In your example, you assume that variable labels would a transformation of the current variable names. But in some other cases, a user would want to update variable labels based on the current existing variable labels.

Therefore, I have introduced two things that I think are more generic.

First, `var_label()<-`, when applied on a data.frame, now accepts a character vector of same length as the number of columns in the data.frame.

Second, I have added a `.labels` argument to `set_variable_labels()` to provide a list of labels, with the same syntax as `var_label()<-`.

Therefore, you can now do something like:

```
new_test_data <- test_data %>%
  set_variable_labels(.labels = make_label(names(test_data)))
```

See also examples provided with `set_variable_labels()` in the dev version of `labelled`.

**Comment by karissawhiting** [comment]
This is awesome. Thank you!
