### ISSUE TITLE
variable labels are not preserved with dplyr functions

### ISSUE THREAD

**Issue by studerus** [larmarange/labelled#39]
If I set a variable label with set_variable_labels and later apply dplyr::filter, the variable label is removed. Here's a small example:

```
library(dplyr)
library(labelled)

df <- tibble(id = 1:2, can = factor(c('yes', 'no'))) %>% 
  set_variable_labels(can = 'Cannabis use')

#variable label is there
df$can

#variable label is not there
filter(df, id == 1)$can

```

I'm not sure if this is a bug of dplyr or of the labelled package. It seems to have been introduced with dplyr version 0.8

**Comment by larmarange** [comment]
Thanks for the report.

You are right, it seems related to the last version of `dplyr` and to https://github.com/tidyverse/dplyr/issues/4219

All attributes are dropped (not specifically labels)

**Comment by studerus** [comment]
[Here](https://github.com/tidyverse/dplyr/issues/4079#issuecomment-451341718) they say it's not dplyr's fault. It's also strange that the attribute is only lost, when the variable is of type factor. If the variable is of type character or numeric, the variable label is still preserved.

**Comment by romainfrancois** [comment]
dplyr is just an innocent bystander here, here is a simpler reprex: 

``` r
library(labelled)

f <- factor(c("a", "b", "c"))
var_label(f) <- "Some label"
str(f)
#>  Factor w/ 3 levels "a","b","c": 1 2 3
#>  - attr(*, "label")= chr "Some label"
str(f[1:2])
#>  Factor w/ 3 levels "a","b","c": 1 2
```

**Comment by larmarange** [comment]
Unfortunately, it depends on  ` [.factor` which is handled by R core.

For `labelled` vectors, variable labels are preserved.

```
> l <- labelled(1:3, labels = c(no = 1))
> var_label(l) <- "variable"
> str(l)
 'haven_labelled' int [1:3] 1 2 3
 - attr(*, "labels")= Named num 1
  ..- attr(*, "names")= chr "no"
 - attr(*, "label")= chr "variable"
> str(l[1])
 'haven_labelled' int 1
 - attr(*, "label")= chr "variable"
 - attr(*, "labels")= Named num 1
  ..- attr(*, "names")= chr "no"
```

However, you can use `copy_labels()` function to copy labels from one data.frame to another.

**Comment by larmarange** [comment]
To be compliant with `dplyr` syntax, I just added a `copy_labels_from()` function:

```
filter(df, id == 1) %>% copy_labels_from(df)
```

**Comment by strengejacke** [comment]
`copy_labels()` from _sjlabelled_ also does the trick:

``` r
library(dplyr)
library(sjlabelled)

df <- tibble(id = 1:2, can = factor(c('yes', 'no'))) %>% 
  var_labels(can = 'Cannabis use')

filter(df, id == 1) %>% copy_labels(df) %>% str()
#> Classes 'tbl_df', 'tbl' and 'data.frame':    1 obs. of  2 variables:
#>  $ id : int 1
#>  $ can: Factor w/ 2 levels "no","yes": 2
#>   ..- attr(*, "label")= chr "Cannabis use"
```

<sup>Created on 2019-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by przemo** [comment]
Is there any workaround for this? I can't imagine adding one extra command to an old code (thousands of lines) whenever I executed `filter`, or `select`. Every time the labels are stripped from the tibble.

**Comment by larmarange** [comment]
There is an issue dedicated to that question in `dplyr`: https://github.com/tidyverse/dplyr/issues/2432
