### ISSUE TITLE
Working with old data labels saved with labelled class

### ISSUE THREAD

**Issue by iago-pssjd** [larmarange/labelled#40]
I was using `remove_val_label` to remove labels of some data saved a months ago under labelled class, but since `val_label.labelled` method was deleted, it does not work. I do not know if it would be a good option to include this method again, or there would be another way to remove labels.

**Comment by larmarange** [comment]
You can use `update_labelled()` to transform old `labelled` class to `haven_labelled` and then apply `remove_val_label`.

Regards

**Comment by iago-pssjd** [comment]
Thanks!
