### ISSUE TITLE
Include lookfor in labelled

### ISSUE THREAD

**Issue by briatte** [larmarange/labelled#44]
Hey @juba and @larmarange,

I have been working with labelled survey data lately. Every time I do so, I find Stata far superior to R when it comes to doing some of the most basic things that we need to do when exploring that kind of data…

## Problem

Take variable labels, which are essential to get a grip of any new survey dataset. How is the user supposed to list them all? Variable labels being in the `attributes`, users might want to do this:

```
for each column:
  list variable name and label
```

Unless I am mistaken, this is not easily doable. The user might try this, which won't work:

```r
attr(labelled_data, "label")
apply(labelled_data, 2, attr, "label")
```

What the user actually needs is:

```r
vapply(labelled_data, attr, character(1), "label", exact = TRUE) # or...
sapply(labelled_data, attr, "label") # ... but non-strict and risky: might return partial matches
```

So, to get all variable labels in a easily-searchable format like a data frame, the user needs, at the very least (and these examples do not even preclude partial matching):

```r
data.frame(vapply(labelled_data, attr, character(1), "label"))
tibble::enframe(vapply(labelled_data, attr, character(1), "label"))
```
 
In all cases above, the user needs to be fairly familiar with R to get the labels. Furthermore, a single missing variable label will kill the function with a cryptic message:

```
Error in vapply(labelled_data, attr, character(1), "label") : 
  values must be length 1,
 but FUN(X[[4]]) result is length 0
```

Here, `[[4]]` is the column (variable) where the variable no variable label (`NULL`).

## Solution

I wrote a short function to list and search variable labels.

It is named `var_labels` in the spirit of the `labelled` package by Joseph, from which I took some code to write the `show_values` argument, and it is similar to the [`lookfor` function](https://github.com/juba/questionr/blob/master/R/lookfor.R) that I wrote for `questionr` many years ago (thanks for improving it, Julien!):

```r
#' @param data a labelled data frame
#' @param show_values add a column showing labelled values
#' @param ... character string(s) to match in the variable names or labels
#' @param ignore.case whether to ignore case when matching variable names or labels
#' @return a tibble
var_labels <- function(data, show_values = FALSE, ..., ignore.case = TRUE) {
  
  require(magrittr) # can easily be removed if need be
  require(tibble)   # preferrable in my view to returning a data.frame
  
  # variable labels -> tibble
  vars <- names(data)
  lbls <- tibble::tibble(variable = vars) %>% 
    tibble::add_column(
      label = vapply(vars, function(x) {
        # similar to labelled:::var_label.default
        x <- attr(data[[ x ]], "label", exact = TRUE)
        # handle missing variable labels
        ifelse(is.null(x), NA_character_, x)
      }, character(1))
    )
  
  # add labelled values
  if (show_values) {
    # similar to labelled:::val_labels.haven_labelled
    lbls <- tibble::add_column(
      lbls,
      values = vapply(vars, function(x) {
        x <- attr(data[[ x ]], "labels", exact = TRUE)
        # handle missing no value labels
        if (is.null(x)) {
          NA_character_
        } else {
          x <- paste0("[", x, "] ", names(x))
          paste(x, collapse = " ")
        }
      }, character(1))
    )
  }
  
  # subset to matching rows (a more complex option would be to use `tidyselect`)
  find <- c(...)
  if (length(find)) {
    find <- paste(find, collapse = "|")
    find <- grepl(find, lbls$variable, ignore.case = ignore.case) |
      grepl(find, lbls$label, ignore.case = ignore.case)
    lbls[ find, ]
  } else {
    lbls
  }
  
}
```

(The `vapply` part cannot be written more efficiently due to the possibility of missing values. Using `purrr::attr_getter` does not solve the issue, as `attr_getter` simply wraps around `attr`.)

Example, using some labelled data included in `questionr`:

```r
library(questionr)

data(fertility)
women$unlabelled_test_variable <- 1L

var_labels(women)
var_labels(women, show_values = TRUE)
var_labels(women, "weight", "child") # Stata equivalent: lookfor weight child
var_labels(women, "hiv", show_values = TRUE)
```

Now, I do not know where to submit that function: are any of you interested in including it in `questionr` or `labelled`?

I also submitted a [simpler function](https://github.com/tidyverse/haven/issues/443) to `haven`, and opened [another issue](https://github.com/tidyverse/haven/issues/444) to discuss its search support.

**Comment by larmarange** [comment]
Hi Julien

lookfor in questionr has evolved to display variable labels and there is an
option show_details = TRUE to display value labels as well

Isn't it what you are looking for? Or should this function evolve?

Joseph Larmarange

Le sam. 13 avr. 2019 à 11:38, François Briatte <notifications@github.com> a
écrit :

**Comment by larmarange** [comment]
Here, a reproductive example:

```r
library(questionr)
data(fertility)
lookfor(children)
#>        variable                    label
#> 1      id_child                 Child Id
#> 2      id_woman                Mother Id
#> 3 date_of_birth            Date of birth
#> 4           sex                      Sex
#> 5         alive             Still alive?
#> 6  age_at_death Age at death (in months)
lookfor(children, details = TRUE)
#>        variable                    label          class   type levels
#> 1      id_child                 Child Id        numeric double       
#> 2      id_woman                Mother Id        numeric double       
#> 3 date_of_birth            Date of birth           Date double       
#> 4           sex                      Sex haven_labelled double       
#> 5         alive             Still alive? haven_labelled double       
#> 6  age_at_death Age at death (in months)        numeric double       
#>                   value_labels unique_values n_na na_values na_range
#> 1                                       1584    0                   
#> 2                                       1090    0                   
#> 3                                       1038    0                   
#> 4         [1] male; [2] female             2    0                   
#> 5 [0] no, dead; [1] yes, alive             2    0                   
#> 6                                         22 1442
lookfor(children, "mo")
#>       variable                    label
#> 2     id_woman                Mother Id
#> 6 age_at_death Age at death (in months)
```

**Comment by larmarange** [comment]
As you can see, the current implementation of `lookfor()` in `questionr` does almost the same thing that your proposal. `show_details = TRUE` also provides user-defined missing values or levels for factors.

Two considerations:

- We could add to `lookfor()` a `show_values` option to present something shorter than `show_details` (only variable, label and value_labels). Similarly, we could add a `show_level` options for those working with factors
- It could make sens to provide `lookfor()` directly in `labelled` packages. As `questionr` already imports functions from `labelled`, we could move the code of `lookfor()` in `labelled` and then simply import in `questionr` that functions from `labelled`.

**Comment by briatte** [comment]
Hey @larmarange 

Correct, this is what I was looking for, thanks a lot!

Re: whether the function be in `questionr` or `labelled`, I still wonder. To me, it would make sense if `labelled` could print all variable labels easily, but the current implementation in `questionr` goes way further than that, since it almost prints out a complete codebook, and that clearly belongs in `questionr` rather than in `questionr`.

So, to conclude, the status quo is pretty good, although I'm going to ask `haven` developers to have a bit of interactivity (meaning, convenience functions to show and search variable and value labels) on their end too.
