### ISSUE TITLE
Working with haven_labelled_spss - data looses “label” after setting NA values

### ISSUE THREAD

**Issue by mspittler** [larmarange/labelled#48]
Sorry to bother, may I point you to an unanswered question at *stackoverflow*. I am not sure whether I make a mistake or there is an unwanted behavior in the package, but `haven_labelled_spss` data seems to less the `label` attribute after using any form of `na_values`. Many thanks!

[https://stackoverflow.com/questions/56235144/working-with-haven-labelled-spss-data-looses-label-after-setting-na-values](https://stackoverflow.com/questions/56235144/working-with-haven-labelled-spss-data-looses-label-after-setting-na-values)

**Comment by larmarange** [comment]
It was a bug in `labelled`. It should be fixed in the development version.
