### ISSUE TITLE
lookfor detail = TRUE not working with haven_labelled

### ISSUE THREAD

**Issue by NoahMarconi** [larmarange/labelled#52]
The if check only looks for "labelled" class and misses "haven_labelled". 

Corrected in this fork: https://github.com/NoahMarconi/labelled/commit/4001267a8d7b3183a412fdfaddb9bb44d3f330ef

I also needed a JSON format. If you're open to a commit like that I can edit to make the JSON optional (e.g. prefixed or JSON) and submit a pull request.

**Comment by larmarange** [comment]
Thanks for having identified this bug. It's now fixed.

Regarding JSON format, could please open a new issue and describe more precisely your need.
Why do you think it should be relevant to provide a JSON export in this function?

I'm in general reluctant to add additional dependencies if the need is too specific.
