### ISSUE TITLE
Value Label in Machine Readable Format (lookfor details = TRUE)

### ISSUE THREAD

**Issue by NoahMarconi** [larmarange/labelled#54]
Currently `levels`, `value_labels`, `na_values`, and `na_range` are converted to a string e.g.: https://github.com/larmarange/labelled/blob/master/R/lookfor.R#L96

The current functionality is useful for `View`ing but less useful when the labels are needed for further processing (e.g. to display labels in a chart or graphic).

Could we add the option to use a machine readable format like `json`, or to preserve the original vectors by storing them in a column of type `<list>`?

`jsonlite::toJSON` can be imported lazily using `Suggests` in the Description file, or no additional dependencies are needed if a flag is added to preserve the original vectors.

**Comment by NoahMarconi** [comment]
I should add, preserving the original vectors works on a `tibble` but would break on a `data.frame`.

**Comment by larmarange** [comment]
Would you have a case scenario? with a concrete example?

If you need a list, you can directly use `var_label()` or `val_labels()`.

``` r
library(labelled)
library(questionr)
#> 
#> Attachement du package : 'questionr'
#> The following object is masked from 'package:labelled':
#> 
#>     look_for
data(fertility) # from questionr, to have households, a labelled dataset
val_labels(households)
#> $id_household
#> NULL
#> 
#> $size
#> NULL
#> 
#> $sex_head
#>   man woman 
#>     1     2 
#> 
#> $structure
#>                              no adult                             one adult 
#>                                     0                                     1 
#>                 one man and one woman                two adults of same sex 
#>                                     2                                     3 
#> three adults or more with family ties             adults with no family tie 
#>                                     4                                     5 
#> 
#> $wealth
#> very poor      poor    medium      rich very rich 
#>         1         2         3         4         5
var_label(households)
#> $id_household
#> [1] "Household Id"
#> 
#> $size
#> [1] "Household size (number of members)"
#> 
#> $sex_head
#> [1] "Sex of household head"
#> 
#> $structure
#> [1] "Household's demographic structure"
#> 
#> $wealth
#> [1] "Wealth index (quintiles)"
```

**Comment by NoahMarconi** [comment]
There's not much more to my use case, I need to import a SAV files, parse them, then extract any metadata the columns contains such as column labels, value labels, etc. 

From there I share the metadata with my client-side reporting application in a structured format so that it can report on labels correctly (instead of bar charts with 1, 2, 3, 4, as labels the client side application shows the correct value labels).

The table returned from `lookfor(df, details = TRUE)` is almost exactly what I need if only the labels are machine readable. 

I can reconstruct from the same functions `lookfor` makes use of (`val_labels` and `var_label`) but notes like this (https://github.com/larmarange/labelled/blob/master/R/lookfor.R#L73) suggest to get what I need, I would have to replicate the functionality in `lookfor` with one modification to show the `value_labels` column in a machine readable format.

**Comment by larmarange** [comment]
This is a quite specific need and for programmatic purpose, two persons will require two different formats.

I still think it belongs much more to your custom function, rather than directly in `labelled` package.

Best regards
