### ISSUE TITLE
Other forms of attributes

### ISSUE THREAD

**Issue by sda030** [larmarange/labelled#56]
The `labelled` and `sjlabelled` packages are especially useful when automating the production of tables, graphs, and other results from real data. However, I have a few ideas for in-house (possibly worthy of sharing with others) functions that are analogous to the labels, but instead specify whether the columns in a data set are dependent, mediator, or independent variables; and whether they are ordinal or nominal (if categorical/labelled). With some easy-to-use functions that keep these attributes when performing e.g. tidyverse-operations, it would be very easy to produce large amounts of graphs where some functions down the pipeline "understand" what should go on the x-axis, y-axis, caption, etc. 
Sure, it is easy to add regular attributes with `attr(df$my_var, "type_of_variable") <- "independent"` , but the ecosystem of functions in this/these packages seem convenient for the same purpose. Though, I am not sure whether there should be a fixed attribute that is called "vartype", or just some generic functions for the user to define one's own attributes.

**Comment by larmarange** [comment]
Dear @sda030 

the main purpose of `labelled` is to follow the `haven_labelled` class introduced by `haven.`

As far as I understood, your proposal is around attributes specifying the role a variable should have in certain analysis. It makes sense in the context of packages such as `finalplot` or `sjmisc`, but I'm not sure in the context of `labelled` focusing only on data type.

Maybe, it would be worth to consider a dedicated package that could be shared between these packages on data analysis. But you will have to raise the discussion with their corresponding authors.

Best regards
