### ISSUE TITLE
feature idea: could recode concatenate combined value labels?

### ISSUE THREAD

**Issue by jdjohn215** [larmarange/labelled#61]
First, thanks for this package, Joseph. I'm a heavy user of it, including in my package for simple weighted survey data [`pollster`](https://github.com/jdjohn215/pollster). The close integration of `haven` and `labelled` has allowed me to transition more of my organization's workflow into R.

Do you think it would be possible to add a feature to `recode` that concatenates the value labels when values are combined in the recoded variable?

Here is an example of what I mean. Here I'm recoding 5-category party ID to 3-category.

```
# the data
d <- structure(list(pid5 = structure(c(1, 2, 3, 4, 5, 9), 
                                             label = "Party ID 5 categories, leaners separate", 
                                             labels = c(Rep = 1,
                                                        `Lean Rep` = 2, 
                                                        Ind = 3, 
                                                        `Lean Dem` = 4, 
                                                        Dem = 5, 
                                                        `Other/None` = 9), 
                                             class = "haven_labelled")), 
                      row.names = c(NA, -6L), 
                      class = c("tbl_df", "tbl", "data.frame"))
```

It looks like this:
```
> d
# A tibble: 6 x 1
            pid5
       <dbl+lbl>
1  1 [Rep]       
2 2 [Lean Rep]  
3 3 [Ind]       
4 4 [Lean Dem]  
5 5 [Dem]       
6 9 [Other/None]
```

Here is the recode, combining the partisans with those who lean to the party.
```
d %>%
  mutate(pid3 = recode(pid5,
                       `1` = 1,
                       `2` = 1,
                       `3` = 2,
                       `4` = 3,
                       `5` = 3,
                       `9` = 9,
                       .default = NaN)) %>%
  # manually set the value labels
  set_value_labels(
    pid3 = c("Rep or Lean Rep" = 1,
             "Ind" = 2,
             "Dem or Lean Dem" = 3,
             "Other/None" = 9)
  )
# A tibble: 6 x 2
            pid5                pid3
       <dbl+lbl>           <dbl+lbl>
1 1 [Rep]        1 [Rep or Lean Rep]
2 2 [Lean Rep]   1 [Rep or Lean Rep]
3 3 [Ind]        2 [Ind]            
4 4 [Lean Dem]   3 [Dem or Lean Dem]
5 5 [Dem]        3 [Dem or Lean Dem]
6 9 [Other/None] 9 [Other/None]     
```

It would be great if the `set_value_labels` portion of that code chunk could be performed automatically. I've tried to write a wrapper doing this myself, but I don't think I understand named vectors well enough to pull it off. Perhaps it's not a realistic idea.

**Comment by larmarange** [comment]
Dear @jdjohn215 

thank you very much for your interest. Just some considerations:

- we cannot guess that a user specifically wants when recoding (there are many different cases) and such feature, if implemented, should be an option (an additional argument);
- however, it has to cover all situations for implementation directly in `labelled` and it is probably not easy considering all the different scenarios:
    - it is not mandatory to provide all observed values in `recode()`
    - you need to consider `.default` and `.missing`
    - all values in the original vector do not always have a value label. So if you merge together a value without label and a value with a label, what should be the new label?
    - what are the treatments to be done regarding user-defined missing values?
- I'm thinking that often the best practice for users would be to say explicitly what they want regarding their value labels.

So, not sure yet how to best deal with your question.

**Comment by larmarange** [comment]
I may have come with a possible solution with an option `.combine_value_labels`.

```r
library(labelled)
x <- labelled(1:4, c("strongly agree" = 1, "agree" = 2, "disagree" = 3, "strongly disagree" = 4))
dplyr::recode(x, `1` = 1L, `2` = 1L, `3` = 2L, `4` = 2L, .combine_value_labels = TRUE)
#> <labelled<integer>[4]>
#> [1] 1 1 2 2
#> 
#> Labels:
#>  value                        label
#>      1       strongly agree / agree
#>      2 disagree / strongly disagree
dplyr::recode(x, `2` = 1L, `4` = 3L, .combine_value_labels = TRUE)
#> <labelled<integer>[4]>
#> [1] 1 1 3 3
#> 
#> Labels:
#>  value                        label
#>      1       strongly agree / agree
#>      3 disagree / strongly disagree
dplyr::recode(x, `2` = 1L, `4` = 3L, .combine_value_labels = TRUE, .sep = " or ")
#> <labelled<integer>[4]>
#> [1] 1 1 3 3
#> 
#> Labels:
#>  value                         label
#>      1       strongly agree or agree
#>      3 disagree or strongly disagree
dplyr::recode(x, `2` = 1L, .default = 2L, .combine_value_labels = TRUE)
#> <labelled<integer>[4]>
#> [1] 2 1 2 2
#> 
#> Labels:
#>  value                                         label
#>      1                                         agree
#>      2 strongly agree / disagree / strongly disagree
```

Can you install the development version of labelled and test it?

**Comment by jdjohn215** [comment]
This is exactly what I imagined! Reading your code in `R/recode.R` was very helpful. Thanks a lot.

I appreciate the complications with combining value labels that you outline above. I completely agree that "the best practice for users would be to say explicitly what they want regarding their value labels." For that reason, have you considered making `.keep_value_labels = FALSE` the default behavior? In my workflow I can easily imagine accidentally copying over value labels which are now incorrect, so I think I will always specify the `FALSE` option.

**Comment by larmarange** [comment]
There is an issue of retrocompatibility here regarding `.keep_value_labels = TRUE` as the `recode()` method is already provided by `labelled` since several releases.
