### ISSUE TITLE
Add a .strict option to set_variable_labels, set_value_labels, set_na_range and set_na_values

### ISSUE THREAD

**Issue by rpruim** [larmarange/labelled#70]
When multiple data sets contain the same variables, it would be nice to define the labeling in a list and then pass that list to `set_variable_labels()` for each data frame.  Some thing like this:

```{r}
labs <- list( x = 'my x lab', y = 'my y lab')
data1 %>% set_variable_labels(labs)
data2 %>% set_variable_labels(labs)
```

Also, it might be nice to have the option `strict = FALSE` to disable checking that all of the labels provided correspond to variables in the data set.  That way if different data sets have different subsets of a master list of variables, the same list can be used to create labels.

**Comment by larmarange** [comment]
For that, you should use the `.labels` option

```r
data1 %>% set_variable_labels(.labels = labs)
```

**Comment by rpruim** [comment]
Ah.  Thanks.  Does that also avoid the error if labels are provided for variables not present in the data?

**Comment by rpruim** [comment]
BTW, The {ggformula} package now supports these labels and uses them in plots. 

Do you know if {ggplot2} has any similar plans?

``` r
suppressPackageStartupMessages(library(ggformula))
data(penguins, package = "palmerpenguins")
penguins %>%
  set_variable_labels(
    bill_length_mm = "bill length (mm)",
    bill_depth_mm = "bill depth (mm)"
  ) %>%
  gf_jitter(bill_length_mm ~ bill_depth_mm | island ~ sex, color = ~ species,
            width = 0.05, height = 0.05, size = 0.5, alpha = 0.6) %>%
  gf_density2d(alpha = 0.3) %>%
  gf_theme(theme_bw()) 
#> Warning: Removed 2 rows containing non-finite values (stat_density2d).
#> Warning: Computation failed in `stat_density2d()`:
#> missing value where TRUE/FALSE needed
#> Warning: Removed 2 rows containing missing values (geom_point).
```

![](https://i.imgur.com/vQhO2OL.png)

<sup>Created on 2020-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
> BTW, The {ggformula} package now supports these labels and uses them in plots.
> 
> Do you know if {ggplot2} has any similar plans?

I don't think so but you should ask directly ggplot2 team

**Comment by larmarange** [comment]
`.strict` is now available in dev version
