### ISSUE TITLE
Request: Downgrade type check in `copy_labels_from()` from error to message.

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/labelled#71]
Hey hey @larmarange !

How do you feel about downgrading the type check error to a message from an error? In the situation below, I need (for whatever reason) to convert a numeric to a character, and I want to re-apply the labels.  

``` r
library(gtsummary)
library(tidyverse)

# convert 
trial2 <-
  trial %>%
  mutate_at(vars(age, marker), as.character)

trial2 %>%
  # copy the labels from the original data frame
  labelled::copy_labels_from(as.data.frame(trial))
#> Error: `from` and `to` should be of same type
```

<sup>Created on 2020-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think in this situation an informative message to the user would be sufficient. For example,
``` r
Column 'age' types do not match in `to=` and `from=` data frames.
Column 'marker' types do not match in `to=` and `from=` data frames.
```

**Comment by larmarange** [comment]
That check was done because when copying value labels or missing values, it is essential that it remains the same type.

But here, you want to copy only variable labels, and in such case it would not be a problem.

I could change the check only for `haven_labelled` vectors and add a `.strict` option: if TRUE will produce an erreor, if FALSE will produce a message only and will copy only variable labels.

**Comment by ddsjoberg** [comment]
OH, ok that makes sense why the check is there.  Thanks!  I use labelled pkg for the smooth variable labelling functions, so I don't have the overall perspective! 🤦 

A strict argument would be helpful to me every once in a while!  Thanks for the great package!

**Comment by larmarange** [comment]
It should have been fixed in the dev version. 

For non-labelled vectors, only variable labels are copied. If `from` is labelled, there is a check about the type of vector and a `.strict` option has been added.

**Comment by ddsjoberg** [comment]
Awesome! Thank you so much!

FYI, the pull request incorporating broom.helpers into gtsummary is now officially undergoing review (https://github.com/ddsjoberg/gtsummary/pull/606).  I added broom.helpers, and made tbl_regression an S3 function to handle the various model types.  Once this is approved and merged, I'll add the multinom method for the nnet muiltinomial regression models 🕺
