### ISSUE TITLE
Cheatsheet

### ISSUE THREAD

**Issue by donnekgit** [larmarange/labelled#76]
First, thank you for an **extremely** useful package.

On the second page of the cheatsheet, under to_labelled(f), "identitical" should read "identical".

In the column heading on that page, "When using labelled data?" might better read "When is labelled data used?", or even (simpler) "What is labelled data?".

**Comment by larmarange** [comment]
Thank you very much @donnekgit for your feedback.

The cheatsheet has been corrected accordingly.
