### ISSUE TITLE
Implementing a recode_if() function preserving variable and value labels

### ISSUE THREAD

**Issue by sda030** [larmarange/labelled#82]
Feature request:
Some conditional recoding requires if_else (or ifelse) rather than recode.haven_labelled. Would be nice if if_else() had a method that saved labels (e.g., .keep_val_labels=TRUE), similar to recode. Simple reprex:

`library(labelled)
library(dplyr)
df <- tibble(s1 = c("M", "M", "F"), s2 = c(2L, 1L, 2L)) %>%
set_variable_labels(s1="Gender", s2="Nurse") %>%
set_value_labels(s1 = c(Male = "M", Female = "F"), s2 = c(Yes = 1L, No = 2L))
mutate(df, s2 = ifelse(s2==2L & s1=="M", NA_integer_, s2)) #  Recodes, but drops variable and value labels :(
mutate(df, s2 = if_else(s2==2L & s1=="M", NA_integer_, s2)) # Fails due to incompatible classes :(
`

There are of course a bunch of dplyr recode-similar verbs that are in line, but I think this one is quite used/useful? Or perhaps a generic method is in order?

(Sorry, unable to get code to adhere to new line)

**Comment by larmarange** [comment]
Hi,

it is raising several issues:

- `dplyr::if_else()` is not a method, cf. https://github.com/tidyverse/dplyr/blob/master/R/if_else.R
- second, this function is very generic in terms of recoding (e.g. could be used to create a completely new variable not related to an existing variable, possibly of any type, or to mix two variables together). Therefore, we cannot assume that variable and value labels should be kept in all cases.

Your situation corresponds to a more specific case consisting of replacing only certain values based on a condition.

The appropriate syntax would be in base R:

```r
df$s3 <- df$s2
df$s3[df$s2 == 2 & df$s1 == "M"] <- NA
```

Such syntax would keep variable and value labels.

To be much more in `dplyr` philosophy, we could create a `if_recode` function. First draft below. Value and variable labels would be ketpt.

``` r
library(labelled) 
library(dplyr) 
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
df <- tibble(s1 = c("M", "M", "F"), s2 = c(2L, 1L, 2L)) %>% 
  set_variable_labels(s1="Gender", s2="Nurse") %>% 
  set_value_labels(s1 = c(Male = "M", Female = "F"), s2 = c(Yes = 1L, No = 2L)) 



if_recode <- function(variable, condition, value) {
  if (length(variable) != length(condition))
    stop("'condition' and 'variable' should have the same length.")
  if (length(value) > 1 & length(value) != length(variable))
    stop("value should be unique or of same length as 'variable'.")
  if (length(value) == 1) {
    variable[condition] <- value
  } else {
    variable[condition] <- value[condition]
  }
  
  variable
}

df$s3 <- df$s2
df$s3[df$s2 == 2 & df$s1 == "M"] <- NA

df <- df %>% mutate(s4 = s2 %>% if_recode(s2 == 2L & s1 == "M", NA))

look_for(df)
#> pos   variable label  col_type values    
#> <chr> <chr>    <chr>  <chr>    <chr>     
#> 1     s1       Gender chr+lbl  [M] Male  
#> <U+200B>      <U+200B>         <U+200B>       <U+200B>         [F] Female
#> 2     s2       Nurse  int+lbl  [1] Yes   
#> <U+200B>      <U+200B>         <U+200B>       <U+200B>         [2] No    
#> 3     s3       Nurse  int+lbl  [1] Yes   
#> <U+200B>      <U+200B>         <U+200B>       <U+200B>         [2] No    
#> 4     s4       Nurse  int+lbl  [1] Yes   
#> <U+200B>      <U+200B>         <U+200B>       <U+200B>         [2] No
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

However, I'm not sure if such function fit the scope of `labelled` or if it would be better to implement it elsewhere (e.g. `dplyr`). To be discussed.

**Comment by larmarange** [comment]
A draft has been added in #83 

Finally, I would prefer the name `recode_if()`
