### ISSUE TITLE
Avoid colonnade()

### ISSUE THREAD

**Issue by krlmlr** [larmarange/labelled#84]
I'd like to retire it the sooner the better, along with a bunch of code and tests only used by that code path.

pillar 1.5.1 offers a battery of extension points that can be used instead, see https://pillar.r-lib.org/articles/extending.html for an intro.

**Comment by larmarange** [comment]
Which function would you recommend as a replacement of `colonnade()`?

**Comment by larmarange** [comment]
Is there an easy solution to remove row IDs? So far, only `colonnade()` is providing a `has_row_id ` option.

It seems that in intern (when looking at the code of `tbl_format_setup()`) you are using a fonction `ctl_colonnade()` but this is not an exported object.

**Comment by krlmlr** [comment]
Thanks for the heads-up. Looks like this problem can be solved with https://github.com/r-lib/pillar/issues/260, I'll prioritize.

**Comment by larmarange** [comment]
@krlmlr 

Thank you very much for your feedback.   In the meantime, I have found an easy solution not using `pillar` but rather base R printing  (here, we used `pillar` just to truncate some columns, that could be done directly with `str_trunc()` without required all `pillar` staff?

However, making it easier to control if and how row ids are printed would be useful in `pilar.`

Do you need a new version of `labelled` withount using `colonnade()` to be released on CRAN? Do you have a specific timeline?

**Comment by krlmlr** [comment]
pillar gives you printing consistent with tibble's output -- if you don't need this, you can use whatever printing method works for you.

I'll implement control for row IDs and get back to you.
