### ISSUE TITLE
sort tagged NAs

### ISSUE THREAD

**Issue by dusadrian** [larmarange/labelled#90]
The usual `sort()` and even `vec_sort()` functions are unable to differentiate between tagged NA values, and they also do not sort according to defined missing values:

``` r
library(haven)
library(labelled)
library(vctrs)
values <- c(3, 1, NA, -9, 2, 4, 5)
labels <- c(Good = 1, Bad = 5, Refuse = -9)
x <- labelled(values, labels = labels)
na_values(x)  <- -9

vec_sort(x)
# <labelled_spss<double>[7]>
# [1] -9  1  2  3  4  5 NA
# Missing values: -9

# Labels:
#  value  label
#      1   Good
#      5    Bad
#     -9 Refuse
```

Since value -9 was defined as a missing value, one would expect the option to sort it after the valid values (however before the regular NA missing values):
``` r
# [1]  1  2  3  4  5 -9 NA
```

Things get even more complex when multiple types of missing values are defined: with or without labels, normal or tagged:

``` r
tags <- tagged_na('a', 'b', 'c')
values <- c(3, 1, tags[3], NA, -9, 2, 4, tags[2], 5, tags[1])
labels <- c(Good = 1, Bad = 5, Refuse = -9, DK = tags[1], NR = tags[2])
x <- labelled(values, labels = labels)
na_values(x)  <- c(-9, tags[1:2])

vec_sort(x)
# <labelled_spss<double>[10]>
#  [1]    -9     1     2     3     4     5 NA(c)    NA NA(b) NA(a)
# Missing values: -9, NA, NA

# Labels:
#  value  label
#      1   Good
#      5    Bad
#     -9 Refuse
#  NA(a)     DK
#  NA(b)     NR
```

Beside -9 being a missing not a valid value, the usual sorting functions do not differentiate between the different tagged NA values.

I've written a function that gives the option to sort according to values or labels, that treats user defined / tagged NAs differently from regular missing values.

``` r
sort_labelled(x)
# <labelled_spss<double>[10]>
#  [1]     1     2     3     4     5    -9 NA(a) NA(b) NA(c)    NA
# Missing values: -9, NA, NA

# Labels:
#  value  label
#      1   Good
#      5    Bad
#     -9 Refuse
#  NA(a)     DK
#  NA(b)     NR
```

Tagged NA values are treated (and sorted) before regular NAs. Users are given complete control on how to sort:

``` r
sort_labelled(x, user_na = "first")
# <labelled_spss<double>[10]>
#  [1]    -9 NA(a) NA(b)     1     2     3     4     5 NA(c)    NA
# Missing values: -9, NA, NA

# Labels:
#  value  label
#      1   Good
#      5    Bad
#     -9 Refuse
#  NA(a)     DK
#  NA(b)     NR
```

or in descending order:

``` r
sort_labelled(x, user_na = "first", na_value = "first", decreasing = TRUE)
# <labelled_spss<double>[10]>
#  [1]    NA NA(c) NA(b) NA(a)    -9     5     4     3     2     1
# Missing values: -9, NA, NA

# Labels:
#  value  label
#      1   Good
#      5    Bad
#     -9 Refuse
#  NA(a)     DK
#  NA(b)     NR
```

or even according to labels:

``` r
sort_labelled(x, according_to = "labels")
# <labelled_spss<double>[10]>
#  [1]     2     3     4     5     1 NA(a) NA(b)    -9 NA(c)    NA
# Missing values: -9, NA, NA

# Labels:
#  value  label
#      1   Good
#      5    Bad
#     -9 Refuse
#  NA(a)     DK
#  NA(b)     NR
```

**Comment by larmarange** [comment]
This point here is similar to #91 

It should not be related to labelled_spss vectors are NAs values should not be passed to `na_range()` (cf #93 )

However, there is an issue for sorting double vectors containing tagged NAs  and a `sort_tagged_na()` function would be relevant.

**Comment by larmarange** [comment]
See draft of `oder_tagged_na()` and `sort_tagged_na()` in https://github.com/larmarange/labelled/blob/324e665ff7ba865f407f6ee1130fccad64ce12cf/R/tagged_na.R

**Comment by dusadrian** [comment]
Thanks, this is almost perfect. It's just that `order_tagged_na()` function outputs doubled indexes:

``` r
order_tagged_na(x)
# [1]  5  2  6  1  7  5 10  8  3  4
```

The index 5 appears twice, with index 9 not being present.

**Comment by larmarange** [comment]
Please check last version.

```
> order_tagged_na(x)
 [1]  5  2  6  1  7  9  4 10  8  3
```

**Comment by dusadrian** [comment]
Thanks very much, I think this closes the issue.
Great function, and I have to admit your version is so much better than mine (kudos).

**Comment by dusadrian** [comment]
Actually, our functions do not completely overlap:

``` r
sort_labelled(x)
#  [1]     1     2     3     4     5    -9 NA(a) NA(b) NA(c)    NA

sort_tagged_na(x)
 # [1]    -9     1     2     3     4     5    NA NA(a) NA(b) NA(c)
```

The "pure" NA value should be placed last, isn't it?

**Comment by larmarange** [comment]
Both tagged and untagged nas are `NA` ("pure" `NA`). These values have a tag or do not have a tag.

In `sort_tagged_na()`, the `na.last` parameter is used for all tagged and untagged `NA` to place them at the beginning of at the end.

Then, there is the question of sorting tagged and untagged NA together. The simplest approach is to sort them alphabetically: so `NA` is sorted before `NA(a)` in ascending order. `na_decreasing` allows you to decide if you want ascending or decreasing order for NA values.

I do not think we need to make things more complex.

**Comment by dusadrian** [comment]
It's true that both tagged and untagged nas are `NA` values, my distinction is theoretical because it matters whether a missing value has or doesn't have a tag.

One possible use (among others) of such a function is to sort these values in a table of frequency:
- we want the valid values first,
- then the defined missing values (SPSS style) / or the tagged NA values (Stata style)
- and only at the end the untagged NA missing values (Sysmis in SPSS, or a `.` in Stata)

This is the way both Stata and SPSS presents the values, so it is important to sort in this very specific way.

**Comment by larmarange** [comment]
OK  and with an option untagged_na_last?

``` r
library(labelled)

tags <- tagged_na('a', 'b', 'c')
values <- c(3, 1, tags[3], NA, -9, 2, 4, tags[2], 5, tags[1])
labels <- c(Good = 1, Bad = 5, Refuse = -9, DK = tags[1], NR = tags[2])
x <- labelled(values, labels = labels)

sort_tagged_na(x)
#> <labelled<double>[10]>
#>  [1]    -9     1     2     3     4     5 NA(a) NA(b) NA(c)    NA
#> 
#> Labels:
#>  value  label
#>      1   Good
#>      5    Bad
#>     -9 Refuse
#>  NA(a)     DK
#>  NA(b)     NR
sort_tagged_na(x, untagged_na_last = FALSE)
#> <labelled<double>[10]>
#>  [1]    -9     1     2     3     4     5    NA NA(a) NA(b) NA(c)
#> 
#> Labels:
#>  value  label
#>      1   Good
#>      5    Bad
#>     -9 Refuse
#>  NA(a)     DK
#>  NA(b)     NR

sort_tagged_na(x, na_decreasing = TRUE)
#> <labelled<double>[10]>
#>  [1]    -9     1     2     3     4     5 NA(c) NA(b) NA(a)    NA
#> 
#> Labels:
#>  value  label
#>      1   Good
#>      5    Bad
#>     -9 Refuse
#>  NA(a)     DK
#>  NA(b)     NR
sort_tagged_na(x, na_decreasing = TRUE, untagged_na_last = FALSE)
#> <labelled<double>[10]>
#>  [1]    -9     1     2     3     4     5    NA NA(c) NA(b) NA(a)
#> 
#> Labels:
#>  value  label
#>      1   Good
#>      5    Bad
#>     -9 Refuse
#>  NA(a)     DK
#>  NA(b)     NR
```

<sup>Created on 2021-04-13 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dusadrian** [comment]
Much better, but when using this option `untagged_na_last` I would actually expect the "pure" NAs to be placed last.
Looks like the outputs should be exactly reversed, am I right?

With `sort_tagged_na()` taking care of the Stata style missing values, I am not sure if you consider a function `sort_labelled()`, because SPSS style missing values should be sortable too.

```r
aa <- labelled_spss(c(3, 1, 2, -9, 4, 5), na_values = -9, labels = c(DK = -9))

sort(aa)
# <labelled_spss<double>[6]>
# [1] -9  1  2  3  4  5
# Missing values: -9

# Labels:
#  value label
#     -9    DK

sort_labelled(aa)
# <labelled_spss<double>[6]>
# [1]  1  2  3  4  5 -9
# Missing values: -9

# Labels:
#  value label
#     -9    DK
```

In the last command, -9 is placed after the highest valid value (5) because it is defined as a missing value.

**Comment by larmarange** [comment]
> Much better, but when using this option `untagged_na_last` I would actually expect the "pure" NAs to be placed last.
> Looks like the outputs should be exactly reversed, am I right?

If you look at the function, by default `untagged_na_last` is TRUE. So the function returns as expected.

**Comment by larmarange** [comment]
Sorting a labelled vector is another topic. -> moved to new issue #97

**Comment by dusadrian** [comment]
Right, for some reason I first read `untagged_na_last = TRUE`, but otherwise this is now great, thanks very much.
