### ISSUE TITLE
declared missing value incorrectly treated in arithmetic operations

### ISSUE THREAD

**Issue by dusadrian** [larmarange/labelled#92]
With normal vectors, missing values do have an effect over arithmetic operations, for instance:

``` r
v1 <- c(1, 2, 1, 2, NA)

mean(v1)
# [1] NA

mean(v1, na.rm = TRUE)
# [1] 1.5
```

In case of labelled vectors with declared missing values, I would have expected the same, but...:

``` r
v2 <- labelled(c(1, 2, 1, 2, -9), labels = c(DK = -9))
na_values(v2) <- -9

# where
is.na(v2)
# [1] FALSE FALSE FALSE FALSE  TRUE

mean(v2)
# [1] -0.6 ???
```

**Comment by larmarange** [comment]
Please see #93 

For me, when a user wants to treat user NAs as proper NAs, it should explicitly use `mean(user_na_to_na(v2))`.

User NAs are an intermediate format to indicate that some values could be treated as missing values. But it remains always necessary to explicitly convert them into proper NAs before analysis (and similarly, labelled vectors representing categorical variables have to be converted into proper factors before analysis).

However, we could see if new functions / facilities are needed to help the user. And a dedicated vignette should be relevant.

**Comment by dusadrian** [comment]
Thank you, indeed a vignette should be relevant.
It would immensely help to clarify (or better solve the inconsistencies between user defined NAs and tagged NAs, which is obviously beyond the package **labelled**, having its origin in package **haven**.

I will also comment on issue 93, but also use the reprex from this issue. It is true that tagged NAs have been introduced to "reproduce the way Stata or SAS works", but it should be made obvious that Stata and SAS use tagged NAs as <user defined> missing values.

All software: SPSS, Stata and SAS basically do exactly the same thing: differentiate between different missing values, just in different ways. SPSS users define missing values as real numbers, while Stata and SAS users do the same: define missing values using tagged numbers. But everywhere those missing values are user defined.

To mimic Stata:

``` r
v3 <- labelled(c(1, 2, 1, 2, tagged_na('a')), labels = c(DK = tagged_na('a')))
na_values(v3) <- tagged_na('a')

# where
is.na(v3)
# [1] FALSE FALSE FALSE FALSE  TRUE

mean(v3)
# [1] NA
```

This example works as intended, the only difference from `v2` being how missing values are (user) defined: as real numbers or (here) as tagged NAs.
