### ISSUE TITLE
Subsetting / indexing on labelled vectors not working

### ISSUE THREAD

**Issue by dusadrian** [larmarange/labelled#95]
One of the extraordinary advantages of labelled vectors is that it allows social scientists (such as myself) to better work in R, where different categories are given allocated (sometimes negative) numbers, something impossible using regular R factors.

It basically boosts social scientists with the possibility to directly import SPSS datasets into R. But just like in SPSS, users should be allowed to subset their data based on certain values. 

The following works as expected:

``` r
dataset <- data.frame(
    Gender = labelled(c(1, 2, 1, 1, 2, -9), labels = c('Male' = 1, 'Female' = 2, 'Prefer not to say' = -9)),
    Age = c(29, 18, 19, 22, 37, 45)
)

subset(dataset, Gender == 1)
#   Gender Age
# 1      1  29
# 3      1  19
# 4      1  22
```

while this does not work:

``` r
na_values(dataset$Gender) <- -9

subset(dataset, Gender == 1)
# Error: Can't combine `..1` <labelled_spss<double>> and `..2` <double>.
# Run `rlang::last_error()` to see where the error occurred.
```

The only difference relates to a single user defined missing value. It doesn't make a difference if it was a tagged NA or a real number, the moment it is defined using `na_values()` subsetting becomes impossible. This really is diving social scientists a very difficult time, especially since such functions are supposed to make their lives easier...

It is all related to an additional class `haven_labelled_spss` being added to that variable, the culprit of all these difficulties, when class `haven_labelled` should be enough.

Apart from `labelled_spss` allowing for an `na_range` (which I didn't use), there really should be no difference between these two vectors. However over 99% of the social scientists' variables are `labelled_spss`, which means they will never be able to subset data.

**Comment by larmarange** [comment]
Seems related to https://github.com/tidyverse/haven/issues/534 and should be fixed in `haven`

**Comment by dusadrian** [comment]
Actually, this is still not fixed in haven...
